SwachhBharatAbhiyan.CMS/Controllers/DumpYardController.cs
using System.IO;
using System.Data;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using Newtonsoft.Json;
using SwachBharat.CMS.Bll.Repository.ChildRepository;
using SwachBharat.CMS.Bll.Repository.MainRepository;
using SwachBharat.CMS.Bll.ViewModels.ChildModel.Model;
using SwachhBharatAbhiyan.CMS.Models.SessionHelper;
using System;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Text;
using System.Xml;
using System.Text.RegularExpressions;
using SwachBharat.CMS.Dal.DataContexts;
using GramPanchayat.API.Bll.ViewModels.ChildModel.Model;
using System.Collections.Generic;
namespace SwachhBharatAbhiyan.CMS.Controllers
{
    public class DumpYardController : Controller
    {
        // GET: DumpYard

           IChildRepository childRepository;
           IMainRepository mainRepository;

        public DumpYardController()
        {
            if (SessionHandler.Current.AppId != 0)
            {
                mainRepository = new MainRepository();
                childRepository = new ChildRepository(SessionHandler.Current.AppId);
            }
            else
                Redirect("/Account/Login");
        }
        public ActionResult Index()
        {
            if (SessionHandler.Current.AppId != 0)
            {
                Session["AppName"] = SessionHandler.Current.AppName;
                return View();
            }
            else
                return Redirect("/Account/Login");
        }

        public ActionResult MenuIndex()
        {
            if (SessionHandler.Current.AppId != 0)
            {
                return View();
            }
            else
                return Redirect("/Account/Login");
        }

        public ActionResult AddDumpYardDetails(int teamId = -1)
        {
            if (SessionHandler.Current.AppId != 0)
            {
                DumpYardDetailsVM dump = childRepository.GetDumpYardById(teamId);
                return View(dump);
            }
            else
                return Redirect("/Account/Login");
        }

        [HttpPost]
        public ActionResult AddDumpYardDetails(DumpYardDetailsVM dumpYard, HttpPostedFileBase filesUpload)
        {
            if (SessionHandler.Current.AppId != 0)
            {
                var AppDetails = mainRepository.GetApplicationDetails(SessionHandler.Current.AppId);
                var guid = Guid.NewGuid().ToString().Split('-');
                string image_Guid = DateTime.Now.ToString("MMddyyyymmss") + "_" + guid[1] + ".jpg";

                //Converting  Url to image 
                // var url = string.Format("http://api.qrserver.com/v1/create-qr-code/?data="+ point.ReferanceId);

                var url = string.Format("https://chart.googleapis.com/chart?cht=qr&chl=" + dumpYard.ReferanceId + "&chs=160x160&chld=L|0");

                WebResponse response = default(WebResponse);
                Stream remoteStream = default(Stream);
                StreamReader readStream = default(StreamReader);
                WebRequest request = WebRequest.Create(url);
                response = request.GetResponse();
                remoteStream = response.GetResponseStream();
                readStream = new StreamReader(remoteStream);
                //Creating Path to save image in folder
                System.Drawing.Image img = System.Drawing.Image.FromStream(remoteStream);
                string imgpath = Path.Combine(Server.MapPath(AppDetails.basePath + AppDetails.DumpYardQRCode), image_Guid);
                var exists = System.IO.Directory.Exists(Server.MapPath(AppDetails.basePath + AppDetails.DumpYardQRCode));
                if (!exists)
                {
                    System.IO.Directory.CreateDirectory(Server.MapPath(AppDetails.basePath + AppDetails.DumpYardQRCode));
                }
                img.Save(imgpath);
                response.Close();
                remoteStream.Close();
                readStream.Close();
                dumpYard.dyQRCode = image_Guid;

                DumpYardDetailsVM pointDetails = childRepository.SaveDumpYard(dumpYard,null);


                return Redirect("Index");
            }
            else
                return Redirect("/Account/Login");
        }

        [HttpGet]
        public ActionResult SaveBundel(int teamId = -1)
        {
            if (SessionHandler.Current.AppId != 0)
            {
                //HouseDetailsVM house = childRepository.GetHouseById(teamId);
                //test(house);
                ZoneVM v = new ZoneVM();
                return View(v);


            }
            else
                return Redirect("/Account/Login");
        }

        [HttpPost]
        public ActionResult SaveBundel(ZoneVM zone)
        {

            if (SessionHandler.Current.AppId != 0)
            {
                DumpYardDetailsVM dumpYard = childRepository.GetDumpYardById(-1);
                List<string> list = new List<string>();
                int n = dumpYard.dyId;
                for (int i = 1; i <= zone.id; i++)
                {
                    int number = 1000;
                    string refer = "DYSBA" + (number + n + i);
                    dumpYard.ReferanceId = refer;

                    dumpYard.dyId = 0;
                    var AppDetails = mainRepository.GetApplicationDetails(SessionHandler.Current.AppId);
                    var guid = Guid.NewGuid().ToString().Split('-');
                    string image_Guid = DateTime.Now.ToString("MMddyyyymmss") + "_" + guid[1] + ".jpg";

                    //Converting  Url to image 
                    var url = string.Format("http://api.qrserver.com/v1/create-qr-code/?data=" + dumpYard.ReferanceId);
                    // var url = string.Format("https://chart.googleapis.com/chart?cht=qr&chl=" + house.ReferanceId + "&chs=250x250&chld=L|0");
                    WebResponse response = default(WebResponse);
                    Stream remoteStream = default(Stream);
                    StreamReader readStream = default(StreamReader);
                    WebRequest request = WebRequest.Create(url);
                    response = request.GetResponse();
                    remoteStream = response.GetResponseStream();
                    readStream = new StreamReader(remoteStream);

                    readStream = new StreamReader(remoteStream);
                    //Creating Path to save image in folder
                    System.Drawing.Image img = System.Drawing.Image.FromStream(remoteStream);
                    string imgpath = Path.Combine(Server.MapPath(AppDetails.basePath + AppDetails.DumpYardQRCode), image_Guid);
                    var exists = System.IO.Directory.Exists(Server.MapPath(AppDetails.basePath + AppDetails.DumpYardQRCode));
                    if (!exists)
                    {
                        System.IO.Directory.CreateDirectory(Server.MapPath(AppDetails.basePath + AppDetails.DumpYardQRCode));
                    }
                    img.Save(imgpath);
                    response.Close();
                    remoteStream.Close();
                    readStream.Close();
                    dumpYard.dyQRCode = image_Guid;
                    dumpYard.ReferanceId = dumpYard.ReferanceId;
                    DumpYardDetailsVM dumpYardDetails = childRepository.SaveDumpYard(dumpYard,null);

                    // generate pdf
                    string Filename = "";

                    string cdatetime = DateTime.Now.ToString("_ddmmyyyyhhmmss");

                    Filename = dumpYard.ReferanceId + "(" + cdatetime + ").pdf";
                    string src = AppDetails.baseImageUrlCMS + "/Content/images/img/app_icon_cms.png";


                    string GridHtml = "<div style='width:100%;height: 100%;text-align: center;background: #fff;border : 2px solid black;'><div style='text-align:center;margin-top: 8px;font-size:22px;background: #abd037;'> O </div> <div style='background: #abd037;;font-weight: bold;font-size: 18px;'> " + AppDetails.AppName + "</div><div style='font-size: 15px;background: #abd037;'> House Id: " + dumpYard.ReferanceId + " </div><div style='height:10px;background: #abd037;'></div> <div style='height:10px;background: #fff;'></div><div style='background: #fff;'> <img style='width:250px;height:250px;' src='" + imgpath + "'/> </div></div>";




                    //using (MemoryStream stream = new System.IO.MemoryStream())
                    //{
                    //    StringReader sr = new StringReader(GridHtml);
                    //    var pgSize = new iTextSharp.text.Rectangle(216, 288);
                    //    Document pdfDoc = new Document(pgSize, 1f, 1f, 1f, 1f);
                    //    var path = Path.Combine(Server.MapPath("~/" + AppDetails.basePath + AppDetails.HouseQRCode + "/bundel"), Filename);

                    //    PdfWriter writer = PdfWriter.GetInstance(pdfDoc, new FileStream(path, FileMode.Create));
                    //    pdfDoc.Open();
                    //    var content = writer.DirectContent;
                    //    var pageBorderRect = new Rectangle(pdfDoc.PageSize);

                    //    pageBorderRect.Left += pdfDoc.LeftMargin;
                    //    pageBorderRect.Right -= pdfDoc.RightMargin;
                    //    pageBorderRect.Top -= pdfDoc.TopMargin;
                    //    pageBorderRect.Bottom += pdfDoc.BottomMargin;


                    //    content.SetColorStroke(BaseColor.BLACK);
                    //    content.SetLineWidth(5);
                    //    content.Rectangle(pageBorderRect.Left, pageBorderRect.Bottom, pageBorderRect.Width, pageBorderRect.Height);
                    //    content.Stroke();
                    //    XMLWorkerHelper.GetInstance().ParseXHtml(writer, pdfDoc, sr);
                    //    pdfDoc.Close();
                    //    return File(stream.ToArray(), "application/pdf", Filename);

SwachhBharatAbhiyan.CMS/Areas/Liquid/Views/LiquidDumpYard/Index.cshtml
@{
    Layout = "";
}
@Styles.Render("~/Content/IndexCSS")
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>

@Scripts.Render("~/Scripts/IndexScript")
@*<script src="~/Content/DatatableGrid/DumpYardGrid.js"></script>*@
<script src="~/Areas/Liquid/Content/Script/DatatableGrid/DumpYardGrid.js"></script>
<body>
    <div class="container">
        <br />
        <div style="width:100%; margin:0 auto;">
            <a href="/Liquid/LiquidDumpYard/AddDumpYardDetails" class="btn btn-success btn-sm float-right" type="button">Add Dump Yard</a>
            <label style="display:inline-flex;padding-right:5px" class="float-right">Search:&nbsp;<input type="text" id="s" class="form-control form-control-sm" onkeyup="Search()"></label>
            <table id="demoGrid" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                <thead>
                    @*<tr>
                        <th>ID</th>
                        <th>डंप यार्ड आयडी <br />Dump Yard ID</th>
                        <th>डंप यार्ड पॉइंट<br />Dump Yard Point</th>
                        <th>कचरा पॉईंट मराठी <br />Garbage Point Marathi</th>
                        <th>स्कॅनिफाय कोड <br />Scaniffy Code</th>
                        <th>डाउनलोड <br />Download</th>
                        <th>झोन <br /> Zone</th>
                        <th>वार्ड क्रमांक <br /> Ward No.</th>
                        <th>क्षेत्र <br /> Area</th>
                        <th>पत्ता <br />Address</th>
                        <th data-sortable="false">क्रिया<br />Action</th>
                    </tr>*@

                    <tr>
                        <th>ID</th>
                        <th> Dump Yard ID</th>
                        <th> Dump Yard Point</th>
                        <th> Garbage Point Marathi</th>
                        <th> Scaniffy Code</th>
                        <th> Download</th>
                        <th> Zone</th>
                        <th> Ward / Prabhag</th>
                        <th> Area</th>
                        <th> Address</th>
                        <th data-sortable="false"> Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</body>

SwachhBharatAbhiyan.CMS/Areas/Liquid/Views/LiquidDumpYard/MenuIndex.cshtml
@{
    //ViewBag.Title = "डंप यार्ड  नोंदणी";
    ViewBag.Title = "Dump Yard Registration";
}

<header class="page-header">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">Dump Yard Registration</h2>
    </div>
</header>
<iframe width="100%" height="600px" src="Index" frameborder="0">
    <p>Your browser does not support iframes.</p>
</iframe>

SwachhBharatAbhiyan.CMS/Areas/Liquid/Views/LiquidDumpYard/SaveBundel.cshtml
@model SwachBharat.CMS.Bll.ViewModels.ChildModel.Model.ZoneVM
@{
    ViewBag.Title = "SaveBundel";
}

<h2>SaveBundel</h2>

@using (@Html.BeginForm("SaveBundel", "DumpYard", FormMethod.Post))
{

    @Html.Label("Total")
    @Html.TextBoxFor(model => model.id)
    <button type="submit">Save</button>
}